shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Meta:
    ordering = ('name', )
    verbose_name = 'category'
    verbose_name_plural = 'categories'

    def __str__(self):
            return self.name
            
    def get_absolute_url(self):
            return reverse('shop:product_list_by_category', args=[self.slug])



class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

class Meta:
    ordering = ('name', )
    index_together = (('id', 'slug'),)

    def __str__(self):
            return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail', args=[self.id, self.slug])



shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

# Create your views here.


def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	products = Product.objects.filter(available=True)
	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = Product.objects.filter(category=category)

	context = {
    	'category': category,
    	'categories': categories,
    	'products': products
	}
	return render(request, 'shop/product/list.html', context)


def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	context = {
    	'product': product
	}
	return render(request, 'shop/product/detail.html', context)

shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}On-line Shop{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
{% include 'shop/navbar.html' %}

{% block content %}

{% endblock %}

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
</body>
</html>

shop/templates/shop/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0px; background-color: #5AC8FA;">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container-fluid">
  	<div class="navbar-header">
	<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
  	<span class="sr-only">Toggle navigation</span>
  	<span class="icon-bar"></span>
  	<span class="icon-bar"></span>
  	<span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="{% url 'shop:product_list' %}" style="color: #ffffff">Henrylab Network</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	<ul class="nav navbar-nav navbar-right">
  	<li class="dropdown">
      	{% if request.user.is_authenticated %}
    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
    	<ul class="dropdown-menu">
      	<li><a href="">logout</a></li>
        	{% else %}
      	<li class="divider"></li>
      	<li><a href="#" style="color: #ffffff">Sign in</a></li>
     	<li><a href="#" style="color: #ffffff">Sign up</a></li>
    	</ul>
     	{% endif %}
  	</li>
	</ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>

shop/templates/shop/product/list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
	{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

{% block content %}
   <div class="container-fluid">
  	<div class="row" style="margin-top: 6%">

    	<div class="col-sm-8 blog-main">

      	<div class="blog-post">
          	<div class="row">
              	{% for product in products %}
                  	<div class="col-md-4">
                    	<div class="thumbnail">
                        	<a href="{{ product.get_absolute_url }}">
                            	<img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                        	</a>
                        	<div class="caption">
                            	<h3 class="text-center">
                                	<a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            	</h3>
                            	<p class="text-center">Kshs. {{ product.price }}</p>
                        	</div>
                    	</div>
                  	</div>
              	{% endfor %}
          	</div>


      	</div><!-- /.blog-post -->

    	</div><!-- /.blog-main -->

    	<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
      	<div class="sidebar-module">
        	<h4>Categories</h4>
        	<ol class="list-unstyled">
          	<li {% if not category %} class="active"{% endif %}><a href="{% url 'shop:product_list' %}">All</a></li>
        	{% for c in categories %}

          	<li {% if category.slug == c.slug %} class="active"{% endif %}>
              	<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
          	</li>
        	{% endfor %}
        	</ol>
      	</div>
    	</div><!-- /.blog-sidebar -->

  	</div><!-- /.row -->

	</div><!-- /.container -->
{% endblock %}